### ISSUE TITLE
improve option page

### ISSUE THREAD

**Issue by jumoog** [intro-skipper/intro-skipper#225]
rework the option page before next release

**Comment by AbandonedCart** [comment]
I need to find a way to get 10.9 running so I can stop sitting on the sideline.

**Comment by jumoog** [comment]
> I need to find a way to get 10.9 running so I can stop sitting on the sideline.
> 
> I wonder how safe it would be to run Ethernet cables through the air vent if it’s climate controlled.

I guess there is only one way to find out. 😂

**Comment by AbandonedCart** [comment]
I’m sure some cable exists for Alaska that would work.

**Comment by CasuallyFilthy** [comment]
> I need to find a way to get 10.9 running so I can stop sitting on the sideline.
> 
> I wonder how safe it would be to run Ethernet cables through the air vent if it’s climate controlled.

Use plenum cables, they're designed to be safe in air vents. Regular Ethernet cables pose fire risks in air vents/ducts

**Comment by AbandonedCart** [comment]
It was more of a bad joke. The router is upstairs because there was originally an office up there and the Mac got moved to the basement for the climate control and backup for severe weather. The outlet is practically right under where the router was located. We had to split the routers due to some work requirements for a dedicated connection, so now the one that has a good connection also can't be used for that stuff and the other router is on the opposite end of the house. Meanwhile, the computer that is in range has to be kept on 10.14 because it's got thousands in software that went to subscriptions. I'm basically caught between horrible connection or obsolete OS. I recent;y uncovered an outlet that may allow me to move the Mac in range, though.
